### ISSUE TITLE
Create a Single Choice Question Endpoint

### ISSUE THREAD

**Issue by jdisser** [team-quizki/quizki-backend#11]
Endpoints

/api/question POST {questionData}

CreateQuestionDTO
{
	"userId": 23,
	"text": "RequiredQuestionText",
	"description": "",
	"type": 1,
	"topics": ["string1", "string2", "stringN"],
	"references": ["ref1", "ref2", "refN"],
	"difficulty": 1,
	"choices": [{"text":"choiceText1", "isCorrect":true}, {"text":"choiceText2", "isCorrect":false}]
}

CreatedQuestionDTO
{
	"id": 263,
	"userId": 23,
	"text": "RequiredQuestionText",
	"description": "",
	"type": 1,
	"topics": [{"id":85, "text":"string1"}, {"id":84, "text":"string2"}, {"id":89, "text":"stringN"}],
	"references": [{"id":1191, "text":"ref1"}, {"id":1163, "text":"ref2"}, {"id":2823, "text":"refN"}],
	"difficulty": 1,
	"choices": [{"id":737, "text":"choiceText1", "isCorrect":true}, {"id":982, "text":"choiceText2", "isCorrect":false}]
}

Validations:
Text cannot be blank. Description can be blank.
For Type and Difficulty, if we get values outside the range of our well known constants, thrown an error.
For Topics, there must be at least one, and the length of the text must be greater than or equal to 2.
References could be empty, but if they are added, their length must be greater than 6.
There has to be at least two choices. One of the choices must be correct. The text of the choice must not be blank.
User ID is required to be valid.

Error Message:
Return the field, and describe how the validation was violated.

Associations
Question has many Topics
Topics has many Questions
Question has many References
References has many Questions 
Question has many Choices
Choice has one Question

**Comment by jdisser** [comment]
Getting started on this issue, moved to In Progress

**Comment by haxwell** [comment]
Merged! Thanks!
