### ISSUE TITLE
Create a Choice endpoint

### ISSUE THREAD

**Issue by jdisser** [team-quizki/quizki-backend#14]
Endpoints

/api/choice?question={id} GET returns Choice[] where Question[id]
/api/choice?question={id} POST {Choice} sets Choice
/api/choice/{id} DELETE deletes Choice[id]
/api/choice/{id} PUT edits Choice[id]

Fields

    id: number,
    text: string,
    isCorrect: string,
    sequence: number,
    questionId: number

Associations

Question has many Choices

**Comment by haxwell** [comment]
While we may need this at some point, I'm gonna close it for now. #YAGNI
