### ISSUE TITLE
Create Question Type Endpoint

### ISSUE THREAD

**Issue by jdisser** [team-quizki/quizki-backend#20]
Endpoint

api/questiontype GET 

Returns

{[id: long , text: String]}

Database entity: questionType

init script modified to populate table

populate with 
id: 1
Text: SINGLE

id: 2
Text: MULTIPLE

**Comment by haxwell** [comment]
Closing for now. I don't think this will be necessary. The backend and frontend will just use well known constants. For instance, both will know that 1 = SINGLE, and 2 = MULTIPLE, etc... So there won't be a need to call and get a list of IDs for types. They will be well known.
