### ISSUE TITLE
Implement a DTO for /api/users POST endpoint to simply the API

### ISSUE THREAD

**Issue by jdisser** [team-quizki/quizki-backend#24]
Remove the role object from the user object in the create user endpoint by implementing a Data Transfer Object (DTO).

UserCreateDTO for /api/users POST

`{
	"password":"mypassword",
	"name":"jdisser",
	"roleId":"1",
	"email":"jdisser@somewhere.com",
	"fullname":"Jim Disser"
}`

all fields are required, 
`email` must be well formed,
`email` and `name` must be unique

The backend will send a response DTO

CreatedUserDTO
`{
	"id":"123",
	"name":"jdisser",
	"roleId":"1",
	"email":"jdisser@somewhere.com",
	"fullname":"Jim Disser"
}`

note the password has been removed for security and the `User.id` has been added

Create a `UserService` with methods to `createNewUser` and validate `emailOrNameIsUnique` that take DTOs as parameters and return values.

**Comment by haxwell** [comment]
Closing. Done.
