### ISSUE TITLE
Create an endpoint which will create a new user.

### ISSUE THREAD

**Issue by haxwell** [team-quizki/quizki-backend#3]
We need to be able to call an endpoint which will create a new user.

The URL will be `/api/user`. It will be a POST call.

User Fields

username (unique)
email address (required) (validate well formed) (unique)
full name (required)
password (required) ~~(unique?)~~
demographic (enum)
~~group(?)~~
role (enum)

**Comment by haxwell** [comment]
Sub tickets/tasks/stories - 

Will need an endpoint to verify the username is unique.
Will need an endpoint to verify the email address is unique.
Will need to define valid demographic values.

**Comment by jdisser** [comment]
Hi @haxwell I'm assuming that the endpoint will return the JSON User object just created, with the SQL created id, or if there is a problem some kind of error message. Is this correct for this story?

**Comment by haxwell** [comment]
@jdisser Yes, that is exactly correct. You pass in the data to create the object, that is parsed by the controller/service into variables, and that collection of variables is passed to the repository, which saves the new object. That new object is then converted to JSON and returned to the client as a response to the API call. And as you said, an error message is returned to the client as a response if something bad happens.

You may want to simulate 'something bad happening' by creating your endpoint, and purposely causing an exception (something easy, like a null pointer exception, or array index out of bounds) to see how the process (of client/server call and response) handles that.

**Comment by haxwell** [comment]
Closing.
